travis:
  secure:
    BINSTAR_TOKEN: a0CKg2aD+CZPhb6xhUl10ES6qe2LYvWXuUo7QXRjyDiZqIa/Twm0ym5Z/71ujwnSwB6J0LyXmLETHdmd7Nyc19xzeTG5i0lTOeTqJbR8bIWlcpzNmVnqnMAB7Mcwy9ehInKNYTN9jOBOGNXE6gMYqBx69DDnOXpcgrK379VDR8gFnjglVF6aJoFLUtI6ikFJuPy4ryzOXaUfsIQDZ4uR9RQAxQ2PKGQS+M0ypr6EmQbbvFEDHdCUiVEUx1lBLf8FTtZJzp+ACARKm9OOoNGwj9m3nw+5Q7Dj190X+O9dHQ/2xa8qQq+jNLCKRw6CIkJJ0bQt9+/YjlCE+geHqvIOxvY7m+OaqpmRCuNdIzmgS3p6k+HTT8OxmNVjvXQJ4D6gX2gNhL5zvIJqoSmCWxSZ6MIl3tOikdic2NA9645Vz1i9wCiv6OuiVa2ClC7MHcGlqefljij2LaBhXd9uev7W8HBv6/RDsLwJEnnzSoC7g0whZJCnMJQVTYfoHTPw77NMOA/041uVl6cGlaTIedCTbU7710XJw1gsiMrl/VBv6Xozo4jzl13LpN1uYvGtdbtLptBjngDlw4ifZ/9uGa9YidbuejNgSIu7mtLTCDv6+UPdCirPILTWGUuJkRh6oWNJxPGorJQ2+QtKOKTcEMPl+97nzd3c61IUr5Lcs7UzgYE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
